<a href="https://colab.research.google.com/github/ehsan74814/Machine_Learning/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# define a matrix
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [3]:
# perform SVD
u, s, vt = np.linalg.svd(a)

In [4]:
#print results
print("U Matrix:\n", u)
print("Singular values (diagonal of sigma ):\n", s)
print("V transpose Matrix:\n", vt)

U Matrix:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values (diagonal of sigma ):
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]
V transpose Matrix:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
